### ISSUE TITLE
New 2.1.5 does not sync

### ISSUE THREAD

**Issue by jfikar** [wheatnetwork/wheat-blockchain#35]
I've just upgraded to the new 2.1.5 and it does not sync the blockchain. There are errors in the log file like:

```
...
ValueError: Error short batch syncing, failed to validate blocks 4499897-4499929

2024-02-19T14:23:33.727 full_node wheat.full_node.full_node: ERROR    Error: Err.INVALID_BLOCK_COST, Invalid block from peer: PeerInfo(_ip=IPv4Address('188.163.24.151'), _port=21333) 
2024-02-19T14:23:33.730 full_node full_node_server        : ERROR    Exception: Error short batch syncing, failed to validate blocks 4499897-4499929, PeerInfo(_ip=IPv4Address('188.163.24.151'), _port=21333). Traceback (most recent call l
ast):
  File "/home/fik/wheat-blockchain/wheat/server/ws_connection.py", line 404, in wrapped_coroutine
    result: Message = await coroutine
                      ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/home/fik/wheat-blockchain/wheat/util/limited_semaphore.py", line 37, in acquire
    yield self._available_count
  File "/home/fik/wheat-blockchain/wheat/full_node/full_node_api.py", line 134, in new_peak
    await self.full_node.new_peak(request, peer)
  File "/home/fik/wheat-blockchain/wheat/full_node/full_node.py", line 764, in new_peak
    if await self.short_sync_batch(peer, uint32(max(curr_peak_height - 6, 0)), request.height):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/home/fik/wheat-blockchain/wheat/util/priority_mutex.py", line 77, in acquire
    yield
  File "/home/fik/wheat-blockchain/wheat/full_node/full_node.py", line 606, in short_sync_batch
    raise ValueError(f"Error short batch syncing, failed to validate blocks {height}-{end_height}")
ValueError: Error short batch syncing, failed to validate blocks 4499897-4499929

2024-02-19T14:23:33.732 full_node full_node_server        : ERROR    Exception: Error short batch syncing, failed to validate blocks 4499897-4499929 <class 'ValueError'>, closing connection PeerInfo(_ip=IPv4Address('188.163.24.151'), _po
rt=21333). Traceback (most recent call last):
  File "/home/fik/wheat-blockchain/wheat/server/ws_connection.py", line 425, in _api_call
    response: Optional[Message] = await asyncio.wait_for(wrapped_coroutine(), timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/tasks.py", line 447, in wait_for
    return await fut
           ^^^^^^^^^
  File "/home/fik/wheat-blockchain/wheat/server/ws_connection.py", line 404, in wrapped_coroutine
    result: Message = await coroutine
                      ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/home/fik/wheat-blockchain/wheat/util/limited_semaphore.py", line 37, in acquire
    yield self._available_count
  File "/home/fik/wheat-blockchain/wheat/full_node/full_node_api.py", line 134, in new_peak
    await self.full_node.new_peak(request, peer)
  File "/home/fik/wheat-blockchain/wheat/full_node/full_node.py", line 764, in new_peak
    if await self.short_sync_batch(peer, uint32(max(curr_peak_height - 6, 0)), request.height):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/home/fik/wheat-blockchain/wheat/util/priority_mutex.py", line 77, in acquire
    yield
  File "/home/fik/wheat-blockchain/wheat/full_node/full_node.py", line 606, in short_sync_batch
    raise ValueError(f"Error short batch syncing, failed to validate blocks {height}-{end_height}")
ValueError: Error short batch syncing, failed to validate blocks 4499897-4499929
```

**Comment by wheatnetwork** [comment]
> 我刚刚升级到新的 2.1.5，它不同步区块链。日志文件中有如下错误：
> 
> ```
> ...
> ValueError: Error short batch syncing, failed to validate blocks 4499897-4499929
> 
> 2024-02-19T14:23:33.727 full_node wheat.full_node.full_node: ERROR    Error: Err.INVALID_BLOCK_COST, Invalid block from peer: PeerInfo(_ip=IPv4Address('188.163.24.151'), _port=21333) 
> 2024-02-19T14:23:33.730 full_node full_node_server        : ERROR    Exception: Error short batch syncing, failed to validate blocks 4499897-4499929, PeerInfo(_ip=IPv4Address('188.163.24.151'), _port=21333). Traceback (most recent call l
> ast):
>   File "/home/fik/wheat-blockchain/wheat/server/ws_connection.py", line 404, in wrapped_coroutine
>     result: Message = await coroutine
>                       ^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/contextlib.py", line 222, in __aexit__
>     await self.gen.athrow(typ, value, traceback)
>   File "/home/fik/wheat-blockchain/wheat/util/limited_semaphore.py", line 37, in acquire
>     yield self._available_count
>   File "/home/fik/wheat-blockchain/wheat/full_node/full_node_api.py", line 134, in new_peak
>     await self.full_node.new_peak(request, peer)
>   File "/home/fik/wheat-blockchain/wheat/full_node/full_node.py", line 764, in new_peak
>     if await self.short_sync_batch(peer, uint32(max(curr_peak_height - 6, 0)), request.height):
>        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/contextlib.py", line 222, in __aexit__
>     await self.gen.athrow(typ, value, traceback)
>   File "/home/fik/wheat-blockchain/wheat/util/priority_mutex.py", line 77, in acquire
>     yield
>   File "/home/fik/wheat-blockchain/wheat/full_node/full_node.py", line 606, in short_sync_batch
>     raise ValueError(f"Error short batch syncing, failed to validate blocks {height}-{end_height}")
> ValueError: Error short batch syncing, failed to validate blocks 4499897-4499929
> 
> 2024-02-19T14:23:33.732 full_node full_node_server        : ERROR    Exception: Error short batch syncing, failed to validate blocks 4499897-4499929 <class 'ValueError'>, closing connection PeerInfo(_ip=IPv4Address('188.163.24.151'), _po
> rt=21333). Traceback (most recent call last):
>   File "/home/fik/wheat-blockchain/wheat/server/ws_connection.py", line 425, in _api_call
>     response: Optional[Message] = await asyncio.wait_for(wrapped_coroutine(), timeout=timeout)
>                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/asyncio/tasks.py", line 447, in wait_for
>     return await fut
>            ^^^^^^^^^
>   File "/home/fik/wheat-blockchain/wheat/server/ws_connection.py", line 404, in wrapped_coroutine
>     result: Message = await coroutine
>                       ^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/contextlib.py", line 222, in __aexit__
>     await self.gen.athrow(typ, value, traceback)
>   File "/home/fik/wheat-blockchain/wheat/util/limited_semaphore.py", line 37, in acquire
>     yield self._available_count
>   File "/home/fik/wheat-blockchain/wheat/full_node/full_node_api.py", line 134, in new_peak
>     await self.full_node.new_peak(request, peer)
>   File "/home/fik/wheat-blockchain/wheat/full_node/full_node.py", line 764, in new_peak
>     if await self.short_sync_batch(peer, uint32(max(curr_peak_height - 6, 0)), request.height):
>        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/contextlib.py", line 222, in __aexit__
>     await self.gen.athrow(typ, value, traceback)
>   File "/home/fik/wheat-blockchain/wheat/util/priority_mutex.py", line 77, in acquire
>     yield
>   File "/home/fik/wheat-blockchain/wheat/full_node/full_node.py", line 606, in short_sync_batch
>     raise ValueError(f"Error short batch syncing, failed to validate blocks {height}-{end_height}")
> ValueError: Error short batch syncing, failed to validate blocks 4499897-4499929
> ```
